Repository cncf/techdocs, pull requests merged in 2024-06, with the labels that each got.

#252 Removing Docs Assessment label
  .github/settings.yml
Labels: CI/infra

#256 [CI & docs] Rework of analysis docs + improved checks
  .github/workflows/format-check.yml
  .markdownlint.yaml
  README.md
  analyses/README.md
  docs/analysis/README.md
  docs/analysis/criteria.md
  docs/analysis/howto.md
  docs/analysis/templates/README.md
  docs/analysis/templates/analysis.md
  docs/analysis/templates/implementation.md
  docs/analysis/templates/issue.md
  docs/analysis/templates/issues-list.md
  docs/analysis/templates/umbrella-issue.md
  docs/analytics.md
  docs/repo-setup.md
  docs/searching-documentation.md
  docs/versioning-documentation.md
  docs/website-guidelines-checklist.md
  package.json
Labels: documentation, CI/infra

#257 Analyses README.md copyedits
  analyses/README.md
Labels: documentation
